version: '3'

services:
  web:
    build: .
    image: dogfood/app
    container_name: app
    command: npm run start
    ports:
      - 3000:8080
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: app
